FROM python:3.10-slim AS base
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PIP_NO_CACHE_DIR=1
RUN apt-get update && apt-get install -y --no-install-recommends build-essential && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY app/requirements.v1.txt requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt
COPY app /app/app
EXPOSE 8080
ENV MODEL_NAME=sentiment-imdb MODEL_STAGE=Staging
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]